import {
	chartTable1,
	seriesTable1,
	seriesTable2,
	seriesTable3,
	chartTable4,
	seriesTable4,
} from '@/stores/charts1'

const addition = [
	{
		id: 1,
		name: 'Клиентский спрос',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 2,
		name: 'стратегия',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 3,
		name: 'планирование',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 4,
		name: 'нестандартный подход',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 5,
		name: 'рекламный клаттер',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 6,
		name: 'SWOT-анализ',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 7,
		name: 'тактический формат',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 8,
		name: 'мониторинг активности',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 9,
		name: 'Рейт-карта',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
	{
		id: 10,
		name: 'Ретроконверсия',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.89',
	},
]

const rows = [
	{
		id: 15,
		name: 'Продажи',
		call: '120',
		ant: '4:15',
		loud: '1.89',
		interrupt: '1.04',
		dynamics: '',
		volume: '',
		selected: false,
		classname: 'blue',
		options1: chartTable1,
		series1: seriesTable1,
		options2: chartTable4,
		series2: seriesTable4,
	},
	{
		id: 16,
		name: 'Сервис',
		call: '3.36',
		ant: '5:15',
		loud: '1.72',
		interrupt: '0.93',
		dynamics: '',
		volume: '',
		selected: false,
		classname: 'green',
		options1: chartTable1,
		series1: seriesTable2,
		options2: chartTable4,
		series2: seriesTable4,
	},
	{
		id: 17,
		name: 'Оплата',
		call: '120',
		ant: '4:18',
		loud: '1.45',
		interrupt: '2.58',
		dynamics: '',
		volume: '',
		selected: false,
		classname: 'orange',
		options1: chartTable1,
		series1: seriesTable3,
		options2: chartTable4,
		series2: seriesTable4,
	},
]

export { addition, rows }
