import { defineStore } from 'pinia'
import {
	getNodeFromTree,
	deleteNodeFromTree,
	insertNodeIntoTree,
	randomNumber,
} from '@/utils/utils'

export const useCat = defineStore({
	id: 'cat',
	state: () => ({
		cat: [
			{
				id: '0',
				label: 'Дерево категорий',
				header: 'root',
				level: 0,
				breads: [],
				childs: [],
				children: [
					{
						id: '1',
						label: 'Продажи',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						children: [
							{
								id: '100',
								label: 'Госсектор',
								breads: ['Тема', 'Продажи'],
								level: 2,
								call: randomNumber(20, 50, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [
									{
										id: '1001',
										label: 'ТЭК',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1002',
										label: 'Гидроэнергетика',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1003',
										label: 'Торговля',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1004',
										label: 'Здравоохранение',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1005',
										label: 'Металлургия',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1006',
										label: 'Сети связи',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
								],
							},
							{
								id: '101',
								label: 'Корпоративные',
								breads: ['Тема', 'Продажи'],
								level: 2,
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [
									{
										id: '1011',
										label: 'Норникель',
										breads: ['Тема', 'Продажи', 'Корпоративные'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1012',
										label: 'Сибнефть',
										breads: ['Тема', 'Продажи', 'Корпоративные'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1013',
										label: 'Альфабанк',
										breads: ['Тема', 'Продажи', 'Корпоративные'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
								],
							},
							{
								id: '102',
								label: 'Малый бизнес',
								level: 2,
								breads: ['Тема', 'Продажи'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [
									{
										id: '1021',
										label: 'Услуги населению',
										breads: ['Тема', 'Продажи', 'Малый бизнес'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1022',
										label: 'Ремонт',
										breads: ['Тема', 'Продажи', 'Малый бизнес'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1023',
										label: 'Такси',
										breads: ['Тема', 'Продажи', 'Малый бизнес'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '1024',
										label: 'Образование',
										breads: ['Тема', 'Продажи', 'Малый бизнес'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
								],
							},
							{
								id: '103',
								label: 'Население',
								level: 2,
								breads: ['Тема', 'Продажи'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
						],
					},
					{
						id: '2',
						label: 'Сервис',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [
							{
								id: '201',
								breads: ['Тема', 'Сервис'],
								label: 'Гарантийное обслуживание',
								level: 2,
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [
									{
										id: '2011',
										label: 'Дефект производителя',
										level: 3,
										breads: ['Тема', 'Сервис', 'Гарантийное обслуживание'],
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '2012',
										label: 'Брак',
										level: 3,
										breads: ['Тема', 'Сервис', 'Гарантийное обслуживание'],
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: '2013',
										label: 'Внешние повреждения',
										level: 3,
										breads: ['Тема', 'Сервис', 'Гарантийное обслуживание'],
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
								],
							},
							{
								id: '202',
								breads: ['Тема', 'Сервис'],
								label: 'Предпродажная подготовка',
								level: 2,
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: '203',
								breads: ['Тема', 'Сервис'],
								label: 'Тюнинг',
								level: 2,
								childs: [],
								children: [],
							},
							{
								id: '204',
								breads: ['Тема', 'Сервис'],
								label: 'Страховка',
								level: 2,
								childs: [],
								children: [],
							},
						],
					},
					{
						id: '3',
						label: 'Оплата',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [
							{
								id: '202',
								label: 'Нал',
								level: 2,
								breads: ['Тема', 'Оплата'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: '203',
								label: 'Безнал',
								level: 2,
								breads: ['Тема', 'Оплата'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: '204',
								label: 'Крипто',
								level: 2,
								breads: ['Тема', 'Оплата'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
						],
					},
					{
						id: '8',
						label: 'Регионы',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [
							{
								id: '81',
								label: 'Центр',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: '82',
								label: 'Северо-Запад',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: '83',
								label: 'Юг',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},

							{
								id: '84',
								label: 'Урал',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: '85',
								label: 'Сибирь',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: '86',
								label: 'Дальний восток',
								level: 2,
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								breads: ['Тема', 'Регионы'],
								childs: [],
								children: [],
							},
						],
					},
					{
						id: '4',
						label: 'Жалобы',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: '5',
						label: 'Неисправности',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: '6',
						label: 'Услуги',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: '7',
						label: 'Работа',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: '9',
						label: 'Грубость',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: '10',
						label: 'Остальное',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
				],
			},
		],
		catselect: '1',
		ticked: [],
		selectedPodcategories: [],
	}),
	getters: {
		// rowNum() {
		// 	return this.getSubCat.length
		// },
		// getSubCat() {
		// 	let item = this.cat[0].children.filter((e) => e.label === this.catselect)
		// 	return item[0].children
		// },
		getItem() {
			let item = getNodeFromTree(this.cat[0], this.catselect)
			return item
		},
		getItemChildren() {
			let item = getNodeFromTree(this.cat[0], this.catselect)
			return item.children
		},
		getItemPodcat() {
			let item = getNodeFromTree(this.cat[0], this.catselect)
			return item.children.map((a) => a.label)
		},
		getTickedRows() {
			let rows = []
			if (this.ticked.length > 0) {
				this.ticked.forEach((item) => {
					rows.push(getNodeFromTree(this.cat[0], item))
				})
			}
			return rows
		},
		getTags() {
			return this.selectedPodcategories.map((item) => item.label)
		},
	},
	actions: {
		killNode(id) {
			deleteNodeFromTree(this.cat[0], id)
		},
		addCategory(newItem, id) {
			insertNodeIntoTree(this.cat[0], id, newItem)
		},
		setCatselect(payload) {
			this.catselect = payload
		},
		setTicked(payload) {
			this.ticked = [...payload]
		},
	},
})
