import { defineStore } from 'pinia'
import {
	getNodeFromTree,
	deleteNodeFromTree,
	insertNodeIntoTree,
	randomNumber,
} from '@/utils/utils'

export const useCat = defineStore({
	id: 'cat',
	state: () => ({
		cat: [
			{
				id: 'Все',
				label: 'Все',
				header: 'root',
				level: 0,
				breads: [],
				childs: [],
				children: [
					{
						id: 'Продажи',
						label: 'Продажи',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						children: [
							{
								id: 'Госсектор',
								label: 'Госсектор',
								breads: ['Тема', 'Продажи'],
								level: 2,
								call: randomNumber(20, 50, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [
									{
										id: 'ТЭК',
										label: 'ТЭК',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Гидроэнергетика',
										label: 'Гидроэнергетика',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Торговля',
										label: 'Торговля',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Здравоохранение',
										label: 'Здравоохранение',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Металлургия',
										label: 'Металлургия',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Сети связи',
										label: 'Сети связи',
										breads: ['Тема', 'Продажи', 'Госсектор'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
								],
							},
							{
								id: 'Корпоративные',
								label: 'Корпоративные',
								breads: ['Тема', 'Продажи'],
								level: 2,
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [
									{
										id: 'Норникель',
										label: 'Норникель',
										breads: ['Тема', 'Продажи', 'Корпоративные'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Сибнефть',
										label: 'Сибнефть',
										breads: ['Тема', 'Продажи', 'Корпоративные'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Альфабанк',
										label: 'Альфабанк',
										breads: ['Тема', 'Продажи', 'Корпоративные'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
								],
							},
							{
								id: 'Малый бизнес',
								label: 'Малый бизнес',
								level: 2,
								breads: ['Тема', 'Продажи'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [
									{
										id: 'Услуги населению',
										label: 'Услуги населению',
										breads: ['Тема', 'Продажи', 'Малый бизнес'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Ремонт',
										label: 'Ремонт',
										breads: ['Тема', 'Продажи', 'Малый бизнес'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Такси',
										label: 'Такси',
										breads: ['Тема', 'Продажи', 'Малый бизнес'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Образование',
										label: 'Образование',
										breads: ['Тема', 'Продажи', 'Малый бизнес'],
										level: 3,
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
								],
							},
							{
								id: 'Население',
								label: 'Население',
								level: 2,
								breads: ['Тема', 'Продажи'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
						],
					},
					{
						id: 'Сервис',
						label: 'Сервис',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [
							{
								id: 'Гарантийное обслуживание',
								breads: ['Тема', 'Сервис'],
								label: 'Гарантийное обслуживание',
								level: 2,
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [
									{
										id: 'Дефект производителя',
										label: 'Дефект производителя',
										level: 3,
										breads: ['Тема', 'Сервис', 'Гарантийное обслуживание'],
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Брак',
										label: 'Брак',
										level: 3,
										breads: ['Тема', 'Сервис', 'Гарантийное обслуживание'],
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
									{
										id: 'Внешние повреждения',
										label: 'Внешние повреждения',
										level: 3,
										breads: ['Тема', 'Сервис', 'Гарантийное обслуживание'],
										call: randomNumber(15, 60, 0),
										ant: randomNumber(2, 8, 2),
										loud: randomNumber(2, 12, 2),
										interrupt: randomNumber(1, 15, 2),
										childs: [],
										children: [],
									},
								],
							},
							{
								id: 'Предпродажная подготовка',
								breads: ['Тема', 'Сервис'],
								label: 'Предпродажная подготовка',
								level: 2,
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: 'Тюнинг',
								breads: ['Тема', 'Сервис'],
								label: 'Тюнинг',
								level: 2,
								childs: [],
								children: [],
							},
							{
								id: 'Страховка',
								breads: ['Тема', 'Сервис'],
								label: 'Страховка',
								level: 2,
								childs: [],
								children: [],
							},
						],
					},
					{
						id: 'Оплата',
						label: 'Оплата',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [
							{
								id: 'Нал',
								label: 'Нал',
								level: 2,
								breads: ['Тема', 'Оплата'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: 'Безнал',
								label: 'Безнал',
								level: 2,
								breads: ['Тема', 'Оплата'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: 'Крипто',
								label: 'Крипто',
								level: 2,
								breads: ['Тема', 'Оплата'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
						],
					},
					{
						id: 'Регионы',
						label: 'Регионы',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [
							{
								id: 'Центр',
								label: 'Центр',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: 'Северо-Запад',
								label: 'Северо-Запад',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: 'Юг',
								label: 'Юг',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},

							{
								id: 'Урал',
								label: 'Урал',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: 'Сибирь',
								label: 'Сибирь',
								level: 2,
								breads: ['Тема', 'Регионы'],
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								childs: [],
								children: [],
							},
							{
								id: 'Дальний восток',
								label: 'Дальний восток',
								level: 2,
								call: randomNumber(15, 60, 0),
								ant: randomNumber(2, 8, 2),
								loud: randomNumber(2, 12, 2),
								interrupt: randomNumber(1, 15, 2),
								breads: ['Тема', 'Регионы'],
								childs: [],
								children: [],
							},
						],
					},
					{
						id: 'Жалобы',
						label: 'Жалобы',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: 'Неисправности',
						label: 'Неисправности',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: 'Услуги',
						label: 'Услуги',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: 'Работа',
						label: 'Работа',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: 'Грубость',
						label: 'Грубость',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: 'Остальное',
						label: 'Остальное',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
					{
						id: 'Мета',
						label: 'Категории по метаданным',
						level: 1,
						call: randomNumber(50, 350, 0),
						ant: randomNumber(4, 10, 2),
						loud: randomNumber(2, 12, 2),
						interrupt: randomNumber(1, 15, 2),
						breads: ['Тема'],
						childs: [],
						children: [],
					},
				],
			},
		],
		catselect: 'Все',
		ticked: [],
		selectedPodcategories: [],
	}),
	getters: {
		// rowNum() {
		// 	return this.getSubCat.length
		// },
		// getSubCat() {
		// 	let item = this.cat[0].children.filter((e) => e.label === this.catselect)
		// 	return item[0].children
		// },
		getItem() {
			let item = getNodeFromTree(this.cat[0], this.catselect)
			return item
		},
		getItemChildren() {
			let item = getNodeFromTree(this.cat[0], this.catselect)
			return item?.children
		},
		getItemPodcat() {
			let item = getNodeFromTree(this.cat[0], this.catselect)
			return item.children.map((a) => a.label)
		},
		getTickedRows() {
			let rows = []
			if (this.ticked.length > 0) {
				this.ticked.forEach((item) => {
					rows.push(getNodeFromTree(this.cat[0], item))
				})
			}
			return rows
		},
		getTags() {
			return this.selectedPodcategories.map((item) => item.label)
		},
	},
	actions: {
		killNode(id) {
			deleteNodeFromTree(this.cat[0], id)
		},
		addCategory(newItem, id) {
			insertNodeIntoTree(this.cat[0], id, newItem)
		},
		setCatselect(payload) {
			this.catselect = payload
		},
		setTicked(payload) {
			this.ticked = [...payload]
		},
	},
})
