const words = [
	{
		id: 0,
		label: 'Приветствие',
		name: 'Приветствие',
		keys: ['здравствуйте', 'добрый вечер', 'доброе утро'],
		selected: false,
		score: 4500,
		voc: true,
	},
	{
		id: 1,
		label: 'Прощание',
		name: 'Прощание',
		keys: ['до свидания', 'всего доброго'],
		selected: false,
		score: 4500,
		voc: true,
	},
	{
		id: 2,
		label: 'Жалобы',
		name: 'Жалобы',
		keys: ['претензия', 'сим-карта', 'система'],
		selected: false,
		score: 4500,
		voc: true,
	},
	{
		id: 3,
		label: 'здравствуйте',
		score: 4000,
		selected: false,
		part: 'adv',
	},
	{
		id: 4,
		label: 'добрый вечер',
		score: 3990,
		selected: false,
		part: 'adv',
	},
	{ id: 5, label: 'доброе утро', score: 3995, selected: false, part: 'adv' },
	{ id: 6, label: 'до свидания', score: 3500, selected: false, part: 'adv' },
	{
		id: 7,
		label: 'спасибо за ожидание',
		score: 3400,
		selected: false,
		part: 'f',
	},
	{
		id: 8,
		label: 'всего доброго',
		score: 3400,
		selected: false,
		part: 'adv',
	},
	{ id: 9, label: 'претензия', score: 3000, selected: false, part: 's' },
	{ id: 10, label: 'сим-карта', score: 2900, selected: false, part: 's' },
	{
		id: 11,
		label: 'поменялся номер',
		score: 2700,
		selected: false,
		part: 'f',
	},
	{
		id: 12,
		label: 'оставайтесь на линии',
		score: 2600,
		selected: false,
		part: 'f',
	},
	{ id: 13, label: 'сказать', score: 2396.6, selected: false, part: 'v' },
	{ id: 14, label: 'время', score: 2015.7, selected: false, part: 's' },
	{ id: 15, label: 'говорить', score: 1755.0, selected: false, part: 'v' },
	{ id: 16, label: 'знать', score: 1713.8, selected: false, part: 'v' },
	{ id: 17, label: 'стать', score: 1621.8, selected: false, part: 'v' },
	{ id: 18, label: 'дело', score: 1412.1, selected: false, part: 's' },
	{ id: 19, label: 'жизнь', score: 1389.8, selected: false, part: 's' },
	{ id: 20, label: 'очень', score: 1286.8, selected: false, part: 'adv' },
	{ id: 21, label: 'день', score: 1258.4, selected: false, part: 's' },
	{ id: 22, label: 'новый', score: 1217.5, selected: false, part: 'a' },
	{ id: 23, label: 'рука', score: 1200.6, selected: false, part: 's' },
	{ id: 24, label: 'работа', score: 1058.3, selected: false, part: 's' },
	{ id: 25, label: 'надо', score: 993.2, selected: false, part: 'adv' },
	{ id: 26, label: 'хотеть', score: 991.3, selected: false, part: 'v' },
	{ id: 27, label: 'слово', score: 967.9, selected: false, part: 's' },
	{ id: 28, label: 'идти', score: 957.1, selected: false, part: 'v' },
	{ id: 29, label: 'большой', score: 944.4, selected: false, part: 'a' },
	{ id: 30, label: 'должен', score: 944.2, selected: false, part: 'a' },
	{ id: 31, label: 'место', score: 926.6, selected: false, part: 's' },
	{ id: 32, label: 'иметь', score: 906.7, selected: false, part: 'v' },
	{ id: 33, label: 'лицо', score: 878.0, selected: false, part: 's' },
	{ id: 34, label: 'друг', score: 874.2, selected: false, part: 's' },
	{ id: 35, label: 'нет', score: 874.0, selected: false, part: 'adv' },
	{ id: 36, label: 'глаз', score: 857.6, selected: false, part: 's' },
	{ id: 37, label: 'тоже', score: 841.5, selected: false, part: 'adv' },
	{ id: 38, label: 'видеть', score: 818.2, selected: false, part: 'v' },
	{ id: 39, label: 'вопрос', score: 805.8, selected: false, part: 's' },
	{ id: 40, label: 'дом', score: 792.6, selected: false, part: 's' },
	{ id: 41, label: 'сторона', score: 768.3, selected: false, part: 's' },
	{ id: 42, label: 'думать', score: 755.5, selected: false, part: 'v' },
	{ id: 43, label: 'сделать', score: 743.5, selected: false, part: 'v' },
	{ id: 44, label: 'страна', score: 725.7, selected: false, part: 's' },
	{ id: 45, label: 'жить', score: 725.5, selected: false, part: 'v' },
	{ id: 46, label: 'мир', score: 714.7, selected: false, part: 's' },
	{ id: 47, label: 'последний', score: 712.6, selected: false, part: 'a' },
	{ id: 48, label: 'случай', score: 709.7, selected: false, part: 's' },
	{ id: 49, label: 'голова', score: 709.4, selected: false, part: 's' },
	{ id: 50, label: 'более', score: 706.2, selected: false, part: 'adv' },
	{ id: 51, label: 'делать', score: 701.1, selected: false, part: 'v' },
	{ id: 52, label: 'смотреть', score: 667.2, selected: false, part: 'v' },
	{ id: 53, label: 'ребенок', score: 658.3, selected: false, part: 's' },
	{ id: 54, label: 'конечно', score: 647.3, selected: false, part: 'adv' },
	{ id: 55, label: 'сила', score: 645.8, selected: false, part: 's' },
	{ id: 56, label: 'российский', score: 644.6, selected: false, part: 'a' },
	{ id: 57, label: 'конец', score: 634.7, selected: false, part: 's' },
	{ id: 58, label: 'вид', score: 620.1, selected: false, part: 's' },
	{ id: 59, label: 'система', score: 617.8, selected: false, part: 's' },
	{ id: 60, label: 'работать', score: 611.2, selected: false, part: 'v' },
	{ id: 61, label: 'понять', score: 588.2, selected: false, part: 'v' },
	{ id: 62, label: 'пойти', score: 587.2, selected: false, part: 'v' },
	{ id: 63, label: 'часть', score: 585.4, selected: false, part: 's' },
	{ id: 64, label: 'спросить', score: 573.9, selected: false, part: 'v' },
	{ id: 65, label: 'город', score: 573.4, selected: false, part: 's' },
	{ id: 66, label: 'дать', score: 573.1, selected: false, part: 'v' },
	{ id: 67, label: 'также', score: 569.9, selected: false, part: 'adv' },
	{ id: 68, label: 'понимать', score: 559.7, selected: false, part: 'v' },
	{ id: 69, label: 'получить', score: 557.7, selected: false, part: 'v' },
	{ id: 70, label: 'отношение', score: 557.4, selected: false, part: 's' },
	{ id: 71, label: 'сидеть', score: 538.1, selected: false, part: 'v' },
	{ id: 72, label: 'женщина', score: 533.3, selected: false, part: 's' },
	{ id: 73, label: 'оказаться', score: 531.9, selected: false, part: 'v' },
	{ id: 74, label: 'русский', score: 530.5, selected: false, part: 'a' },
	{ id: 75, label: 'взять', score: 525.8, selected: false, part: 'v' },
	{ id: 76, label: 'прийти', score: 523.3, selected: false, part: 'v' },
	{ id: 77, label: 'являться', score: 522.9, selected: false, part: 'v' },
	{ id: 78, label: 'деньги', score: 512.4, selected: false, part: 's' },
	{ id: 79, label: 'вдруг', score: 503.2, selected: false, part: 'adv' },
	{ id: 80, label: 'любить', score: 503.1, selected: false, part: 'v' },
	{ id: 81, label: 'стоить', score: 501.9, selected: false, part: 'v' },
	{ id: 82, label: 'почти', score: 501.7, selected: false, part: 'adv' },
	{ id: 83, label: 'земля', score: 494.4, selected: false, part: 's' },
	{ id: 84, label: 'общий', score: 492.4, selected: false, part: 'a' },
	{ id: 85, label: 'машина', score: 490.4, selected: false, part: 's' },
	{ id: 86, label: 'сразу', score: 486.0, selected: false, part: 'adv' },
	{ id: 87, label: 'хорошо', score: 485.7, selected: false, part: 'adv' },
	{ id: 88, label: 'вода', score: 484.8, selected: false, part: 's' },
	{ id: 89, label: 'отец', score: 484.1, selected: false, part: 's' },
	{ id: 90, label: 'высокий', score: 483.3, selected: false, part: 'a' },
	{ id: 91, label: 'остаться', score: 482.7, selected: false, part: 'v' },
	{ id: 92, label: 'выйти', score: 480.9, selected: false, part: 'v' },
	{ id: 93, label: 'проблема', score: 474.9, selected: false, part: 's' },
	{ id: 94, label: 'начать', score: 473.3, selected: false, part: 'v' },
	{ id: 95, label: 'хороший', score: 471.4, selected: false, part: 'a' },
	{ id: 96, label: 'час', score: 468.1, selected: false, part: 's' },
	{ id: 97, label: 'сегодня', score: 463.5, selected: false, part: 'adv' },
	{ id: 98, label: 'право', score: 461.4, selected: false, part: 's' },
	{ id: 99, label: 'совсем', score: 460.5, selected: false, part: 'adv' },
	{ id: 100, label: 'нога', score: 459.2, selected: false, part: 's' },
	{ id: 101, label: 'считать', score: 455.3, selected: false, part: 'v' },
	{ id: 102, label: 'главный', score: 454.6, selected: false, part: 'a' },
	{ id: 103, label: 'решение', score: 453.4, selected: false, part: 's' },
	{ id: 104, label: 'увидеть', score: 452.4, selected: false, part: 'v' },
	{ id: 105, label: 'дверь', score: 450.8, selected: false, part: 's' },
	{ id: 106, label: 'казаться', score: 448.2, selected: false, part: 'v' },
	{ id: 107, label: 'образ', score: 445.9, selected: false, part: 's' },
	{ id: 108, label: 'писать', score: 444.3, selected: false, part: 'v' },
	{ id: 109, label: 'история', score: 443.9, selected: false, part: 's' },
	{ id: 110, label: 'лучший', score: 443.2, selected: false, part: 'a' },
	{ id: 111, label: 'власть', score: 435.6, selected: false, part: 's' },
	{ id: 112, label: 'закон', score: 433.4, selected: false, part: 's' },
	{ id: 113, label: 'война', score: 425.9, selected: false, part: 's' },
	{ id: 114, label: 'бог', score: 425.4, selected: false, part: 's' },
	{ id: 115, label: 'голос', score: 424.5, selected: false, part: 's' },
	{ id: 116, label: 'найти', score: 424.1, selected: false, part: 'v' },
]

export { words }
