const marks = [
	{
		id: 0,
		anketa: 'Квартальная',
		selected: false,
		descr: 'Для квартальных оценок',
		date: '2023-12-20',
		supervisor: 'Орлов П.С',
		status: 'В работе',
		mark: 53,
	},
	{
		id: 1,
		anketa: 'По категориям',
		selected: false,
		descr: 'Для оценок категорий',
		date: '2023-11-20',
		supervisor: 'Серегин В.В.',
		status: 'Эскалация',
		mark: 57,
	},
	{
		id: 2,
		anketa: 'Выборочная',
		selected: false,
		descr: 'Разовые проверки',
		date: '2023-10-20',
		supervisor: 'Орлов П.С',
		status: 'В работе',
		mark: 41,
	},
	{
		id: 3,
		anketa: 'По категориям',
		selected: false,
		descr: 'Для оценок категорий',
		date: '2023-09-20',
		supervisor: 'Серегин В.В.',
		status: 'В работе',
		mark: 49,
	},
	{
		id: 4,
		anketa: 'По категориям',
		selected: false,
		descr: 'Для оценок категорий',
		date: '2023-08-20',
		supervisor: 'Орлов П.С',
		status: 'Завершено',
		mark: 46,
	},
	{
		id: 5,
		anketa: 'Квартальная',
		selected: false,
		descr: 'Для квартальных оценок',
		date: '2023-07-20',
		supervisor: 'Воробьев Г.А.',
		status: 'Завершено',
		mark: 63,
	},
	{
		id: 6,
		anketa: 'Выборочная',
		selected: false,
		descr: 'Разовые проверки',
		date: '2023-06-20',
		supervisor: 'Орлов П.С',
		status: 'Завершено',
		mark: 59,
	},
	{
		id: 7,
		anketa: 'Квартальная',
		selected: false,
		descr: 'Для квартальных оценок',
		date: '2023-05-20',
		supervisor: 'Орлов П.С',
		status: 'Завершено',
		mark: 44,
	},
	{
		id: 8,
		anketa: 'По категориям',
		selected: false,
		descr: 'Для оценок категорий',
		date: '2023-04-20',
		supervisor: 'Воробьев Г.А.',
		status: 'Завершено',
		mark: 48,
	},
	{
		id: 9,
		anketa: 'По категориям',
		selected: false,
		descr: 'Для оценок категорий',
		date: '2023-03-20',
		supervisor: 'Орлов П.С',
		status: 'Завершено',
		mark: 39,
	},
	{
		id: 10,
		anketa: 'Квартальная',
		selected: false,
		descr: 'Для квартальных оценок',
		date: '2023-02-20',
		supervisor: 'Воробьев Г.А.',
		status: 'Завершено',
		mark: 43,
	},
	{
		id: 11,
		anketa: 'Выборочная',
		selected: false,
		descr: 'Разовые проверки',
		date: '2023-01-20',
		supervisor: 'Воробьев Г.А.',
		status: 'Завершено',
		mark: 75,
	},
	{
		id: 12,
		anketa: 'По категориям',
		selected: false,
		descr: 'Для оценок категорий',
		date: '2022-12-20',
		supervisor: 'Орлов П.С',
		status: 'Завершено',
		mark: 58,
	},
	{
		id: 13,
		anketa: 'Выборочная',
		selected: false,
		descr: 'Разовые проверки',
		date: '2022-11-20',
		supervisor: 'Воробьев Г.А.',
		status: 'Завершено',
		mark: 48,
	},
]

export { marks }
