const notifications = [
	{
		id: 31,
		name: 'друг',
		channel: 'все',
		time: '15:04:33',
		date: 'сегодня',
		unread: true,
		old: false,
		oper: 'Екатерина',
		context:
			'Velit, scelerisque in <span>dictum</span> non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 13,
		name: 'знать',
		channel: 'клиент',
		time: '15:04:33',
		date: 'сегодня',
		unread: true,
		old: false,
		oper: 'Елена',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 3,
		name: 'до свидания',
		channel: 'оператор',
		time: '15:04:33',
		date: 'сегодня',
		unread: false,
		old: false,
		oper: 'Ирина',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 14,
		name: 'стать',
		channel: 'клиент',
		time: '15:04:33',
		date: 'вчера',
		unread: true,
		old: false,
		oper: 'Ева',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 8,
		name: 'поменялся номер',
		channel: 'оператор',
		time: '15:04:33',
		date: 'вчера',
		unread: true,
		old: false,
		oper: 'Дарья',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 19,
		name: 'новый',
		channel: 'клиент',
		time: '15:04:33',
		date: 'вчера',
		unread: true,
		old: true,
		oper: 'Кира',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 9,
		name: 'оставайтесь на линии',
		channel: 'оператор',
		time: '15:04:33',
		date: 'вчера',
		unread: false,
		old: true,
		oper: 'Елизавета',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 23,
		name: 'хотеть',
		channel: 'клиент',
		time: '15:04:33',
		date: 'вчера',
		unread: true,
		old: true,
		oper: 'Ульяна',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 34,
		name: 'тоже',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-29',
		unread: false,
		old: true,
		oper: 'Татьяна',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 28,
		name: 'место',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-29',
		unread: false,
		old: true,
		oper: 'Юлия',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 10,
		name: 'сказать',
		channel: 'оператор',
		time: '15:04:33',
		date: '2022-05-29',
		unread: true,
		old: true,
		oper: 'Софья',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 37,
		name: 'нормально',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-29',
		unread: false,
		old: true,
		oper: 'Алина',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 26,
		name: 'большой',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-28',
		unread: false,
		old: true,
		oper: 'Злата',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 22,
		name: 'надо',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-28',
		unread: false,
		old: true,
		oper: 'Милана',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 24,
		name: 'слово',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-28',
		unread: false,
		old: true,
		oper: 'Ольга',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 18,
		name: 'день',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-28',
		unread: false,
		old: true,
		oper: 'Катя',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 15,
		name: 'дело',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-28',
		unread: false,
		old: true,
		oper: 'Светлана',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 36,
		name: 'слышать',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-28',
		unread: false,
		old: true,
		oper: 'Ярослава',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 17,
		name: 'очень',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-28',
		unread: false,
		old: true,
		oper: 'Яна',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 27,
		name: 'должен',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Кристина',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 5,
		name: 'всего доброго',
		channel: 'оператор',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Алиса',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 2,
		name: 'доброе утро',
		channel: 'оператор',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Маргарита',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 11,
		name: 'время',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Таисия',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 33,
		name: 'глаз',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Тамара',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 25,
		name: 'идти',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Эмилия',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 20,
		name: 'рука',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Диана',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 30,
		name: 'лицо',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Анфиса',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 21,
		name: 'работа',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Аделина',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 16,
		name: 'жизнь',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Евдокия',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 29,
		name: 'иметь',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Зоя',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 1,
		name: 'добрый вечер',
		channel: 'оператор',
		time: '15:04:33',
		date: '2022-05-26',
		unread: false,
		old: true,
		oper: 'Ираида',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 32,
		name: 'нет',
		channel: 'все',
		time: '15:04:33',
		date: '2022-05-23',
		unread: false,
		old: true,
		oper: 'Наталья',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 12,
		name: 'говорить',
		channel: 'клиент',
		time: '15:04:33',
		date: '2022-05-23',
		unread: false,
		old: true,
		oper: 'Пелагея',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 4,
		name: 'спасибо за ожидание ',
		channel: 'оператор',
		time: '15:04:33',
		date: '2022-05-23',
		unread: false,
		old: true,
		oper: 'Сабина',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 7,
		name: 'сим-карта',
		channel: 'оператор',
		time: '15:04:33',
		date: '2022-05-23',
		unread: false,
		old: true,
		oper: 'Антонина',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 0,
		name: 'здравствуйте',
		channel: 'оператор',
		time: '15:04:33',
		date: '2022-05-23',
		unread: false,
		old: true,
		oper: 'Елена',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
	{
		id: 6,
		name: 'претензия',
		channel: 'оператор',
		time: '15:04:33',
		date: '2022-05-23',
		unread: false,
		old: true,
		oper: 'Алексей',
		context: 'Velit, scelerisque in dictum non, consectetur a erat nam at lectus urna duis',
	},
]

export { notifications }
