const operators = [
	{
		id: 0,
		name: 'Екатерина',
		group: 'Юрлица',
		city: 'Москва',
		total: 169,
		percent: 9,
		good: 15,
		notgood: 47,
		bad: 53,
		date: '2022-12-14',
	},
	{
		id: 1,
		name: 'Елена    ',
		group: 'Физлица',
		city: 'СПб',
		total: 216,
		percent: 43,
		good: 93,
		notgood: 87,
		bad: 29,
		date: '2022-12-05',
	},
	{
		id: 2,
		name: 'Ксения   ',
		group: 'Физлица',
		city: 'СПб',
		total: 283,
		percent: 31,
		good: 87,
		notgood: 83,
		bad: 67,
		date: '2022-12-05',
	},
	{
		id: 3,
		name: 'Ирина    ',
		group: 'Юрлица',
		city: 'Тбилиси',
		total: 255,
		percent: 23,
		good: 59,
		notgood: 20,
		bad: 19,
		date: '2022-12-14',
	},
	{
		id: 4,
		name: 'Ева      ',
		group: 'Юрлица',
		city: 'СПб',
		total: 210,
		percent: 9,
		good: 19,
		notgood: 87,
		bad: 17,
		date: '2022-12-14',
	},
	{
		id: 5,
		name: 'Дарья    ',
		group: 'Юрлица',
		city: 'СПб',
		total: 225,
		percent: 24,
		good: 54,
		notgood: 67,
		bad: 3,
		date: '2022-12-05',
	},
	{
		id: 6,
		name: 'Кира     ',
		group: 'Физлица',
		city: 'Москва',
		total: 209,
		percent: 22,
		good: 45,
		notgood: 37,
		bad: 53,
		date: '2022-12-05',
	},
	{
		id: 7,
		name: 'Елизавета',
		group: 'Физлица',
		city: 'СПб',
		total: 204,
		percent: 31,
		good: 63,
		notgood: 53,
		bad: 86,
		date: '2022-12-14',
	},
	{
		id: 8,
		name: 'Ульяна   ',
		group: 'Юрлица',
		city: 'Москва',
		total: 167,
		percent: 28,
		good: 47,
		notgood: 4,
		bad: 17,
		date: '2022-12-05',
	},
	{
		id: 9,
		name: 'Татьяна  ',
		group: 'Физлица',
		city: 'СПб',
		total: 257,
		percent: 21,
		good: 53,
		notgood: 59,
		bad: 63,
		date: '2022-12-14',
	},
	{
		id: 10,
		name: 'Юлия     ',
		group: 'Юрлица',
		city: 'Москва',
		total: 227,
		percent: 37,
		good: 83,
		notgood: 77,
		bad: 60,
		date: '2022-12-14',
	},
	{
		id: 11,
		name: 'Софья    ',
		group: 'Юрлица',
		city: 'СПб',
		total: 197,
		percent: 16,
		good: 32,
		notgood: 97,
		bad: 37,
		date: '2022-12-05',
	},
	{
		id: 12,
		name: 'Алина    ',
		group: 'Физлица',
		city: 'Москва',
		total: 295,
		percent: 18,
		good: 53,
		notgood: 17,
		bad: 73,
		date: '2022-12-05',
	},
	{
		id: 13,
		name: 'Злата    ',
		group: 'Физлица',
		city: 'СПб',
		total: 244,
		percent: 39,
		good: 96,
		notgood: 19,
		bad: 20,
		date: '2022-12-05',
	},
	{
		id: 14,
		name: 'Милана   ',
		group: 'Физлица',
		city: 'СПб',
		total: 190,
		percent: 38,
		good: 73,
		notgood: 48,
		bad: 46,
		date: '2022-12-14',
	},
	{
		id: 15,
		name: 'Ольга    ',
		group: 'Юрлица',
		city: 'СПб',
		total: 263,
		percent: 18,
		good: 47,
		notgood: 3,
		bad: 32,
		date: '2022-12-14',
	},
	{
		id: 16,
		name: 'Светлана ',
		group: 'Юрлица',
		city: 'Тбилиси',
		total: 176,
		percent: 10,
		good: 17,
		notgood: 54,
		bad: 83,
		date: '2022-12-05',
	},
	{
		id: 17,
		name: 'Ярослава ',
		group: 'Физлица',
		city: 'Москва',
		total: 292,
		percent: 16,
		good: 48,
		notgood: 15,
		bad: 4,
		date: '2022-12-05',
	},
	{
		id: 18,
		name: 'Яна      ',
		group: 'Юрлица',
		city: 'СПб',
		total: 284,
		percent: 11,
		good: 30,
		notgood: 60,
		bad: 77,
		date: '2022-12-05',
	},
	{
		id: 19,
		name: 'Кристина ',
		group: 'Физлица',
		city: 'СПб',
		total: 255,
		percent: 18,
		good: 46,
		notgood: 86,
		bad: 48,
		date: '2022-12-05',
	},
	{
		id: 20,
		name: 'Алиса    ',
		group: 'Юрлица',
		city: 'Тбилиси',
		total: 153,
		percent: 50,
		good: 77,
		notgood: 17,
		bad: 86,
		date: '2022-12-05',
	},
	{
		id: 21,
		name: 'Маргарита',
		group: 'Юрлица',
		city: 'Москва',
		total: 161,
		percent: 60,
		good: 97,
		notgood: 96,
		bad: 70,
		date: '2022-12-05',
	},
	{
		id: 22,
		name: 'Таисия   ',
		group: 'Физлица',
		city: 'Москва',
		total: 235,
		percent: 12,
		good: 29,
		notgood: 29,
		bad: 46,
		date: '2022-12-05',
	},
	{
		id: 23,
		name: 'Тамара   ',
		group: 'Юрлица',
		city: 'Тбилиси',
		total: 203,
		percent: 42,
		good: 86,
		notgood: 45,
		bad: 3,
		date: '2022-12-14',
	},
	{
		id: 24,
		name: 'Эмилия   ',
		group: 'Физлица',
		city: 'Москва',
		total: 231,
		percent: 7,
		good: 17,
		notgood: 73,
		bad: 87,
		date: '2022-12-14',
	},
	{
		id: 25,
		name: 'Диана    ',
		group: 'Юрлица',
		city: 'Тбилиси',
		total: 183,
		percent: 11,
		good: 20,
		notgood: 47,
		bad: 15,
		date: '2022-12-14',
	},
	{
		id: 26,
		name: 'Анфиса   ',
		group: 'Физлица',
		city: 'Тбилиси',
		total: 211,
		percent: 41,
		good: 86,
		notgood: 46,
		bad: 45,
		date: '2022-12-05',
	},
	{
		id: 27,
		name: 'Аделина  ',
		group: 'Юрлица',
		city: 'Москва',
		total: 234,
		percent: 30,
		good: 70,
		notgood: 46,
		bad: 59,
		date: '2022-12-14',
	},
	{
		id: 28,
		name: 'Евдокия  ',
		group: 'Физлица',
		city: 'Тбилиси',
		total: 237,
		percent: 16,
		good: 37,
		notgood: 86,
		bad: 54,
		date: '2022-12-05',
	},
	{
		id: 29,
		name: 'Зоя      ',
		group: 'Физлица',
		city: 'Москва',
		total: 185,
		percent: 36,
		good: 67,
		notgood: 45,
		bad: 87,
		date: '2022-12-14',
	},
	{
		id: 30,
		name: 'Ираида   ',
		group: 'Физлица',
		city: 'Москва',
		total: 215,
		percent: 21,
		good: 45,
		notgood: 53,
		bad: 47,
		date: '2022-12-14',
	},
	{
		id: 31,
		name: 'Наталья  ',
		group: 'Юрлица',
		city: 'Тбилиси',
		total: 276,
		percent: 9,
		good: 24,
		notgood: 32,
		bad: 97,
		date: '2022-12-14',
	},
	{
		id: 32,
		name: 'Пелагея  ',
		group: 'Юрлица',
		city: 'Тбилиси',
		total: 259,
		percent: 18,
		good: 46,
		notgood: 3,
		bad: 47,
		date: '2022-12-05',
	},
	{
		id: 33,
		name: 'Сабина   ',
		group: 'Физлица',
		city: 'Москва',
		total: 156,
		percent: 56,
		good: 87,
		notgood: 63,
		bad: 9,
		date: '2022-12-05',
	},
	{
		id: 34,
		name: 'Антонина ',
		group: 'Юрлица',
		city: 'Тбилиси',
		total: 249,
		percent: 12,
		good: 30,
		notgood: 70,
		bad: 45,
		date: '2022-12-05',
	},
]

const records = [
	{
		id: 0,
		date: '2022-04-25 18:11',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'<span class="emo red gnev">Urna condimentum <span class="found">претензия</span> mattis</span> pellentesque id.',
		operator: 'Екатерина',
		client: 'Григорий',
		expand: false,
		star: true,
		comment: 'Нормально, Григорий? Отлично, Константин. Это комментарий.',
	},
	{
		id: 1,
		date: '2022-04-25 18:10',
		group: 'группа 2',
		categ: 'Оплата',
		record:
			'<span class="emo green radost">Arcu felis, bibendum  <span class="found">претензия</span> ut tristique</span> et, egestas quis? Nisl suscipit adipiscing.',
		operator: 'Елена',
		client: 'Лев',
		expand: false,
		star: true,
		comment: '',
	},
	{
		id: 2,
		date: '2022-04-24 18:09',
		group: 'группа 3',
		categ: 'Сервис',
		record:
			'<span class="emo red sarcazm">Ut placerat orci <span class="found">претензия</span> nulla</span> pellentesque dignissim enim, sit?',
		operator: 'Ксения',
		client: 'Андрей',
		expand: false,
		star: true,
		comment: '',
	},
	{
		id: 3,
		date: '2022-04-24 18:09',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'<span class="emo red loud">In nibh mauris, cursus mattis  <span class="found">претензия</span> molestie a</span>, iaculis.',
		operator: 'Ирина',
		client: 'Роман',
		expand: false,
		star: true,
		comment: '',
	},
	{
		id: 4,
		date: '2022-04-24 18:08',
		group: 'группа 2',
		categ: 'Сервис',
		record:
			'<span class="emo red tone">Id neque aliquam vestibulum  <span class="found">претензия</span></span> morbi blandit cursus risus?',
		operator: 'Ева',
		client: 'Арсений',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 5,
		date: '2022-04-24 16:44',
		group: 'группа 3',
		categ: 'Сервис',
		record:
			'Amet, porttitor eget dolor morbi non  <span class="found">претензия</span> arcu risus!',
		operator: 'Дарья',
		client: 'Степан',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 6,
		date: '2022-04-24 16:43',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'<span class="emo red grust">Varius duis  <span class="found">претензия</span> at consectetur</span> lorem donec massa sapien.',
		operator: 'Кира',
		client: 'Владислав',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 7,
		date: '2022-04-24 16:08',
		group: 'группа 2',
		categ: 'Оплата',
		record:
			'Morbi tincidunt ornare  <span class="found">претензия</span> massa, eget egestas purus viverra.',
		operator: 'Елизавета',
		client: 'Никита',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 8,
		date: '2022-04-24 16:07',
		group: 'группа 3',
		categ: 'Продажи',
		record:
			'Egestas  <span class="found">претензия</span> integer eget aliquet nibh praesent tristique magna?',
		operator: 'Ульяна',
		client: 'Глеб',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 9,
		date: '2022-04-24 16:06',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Lacus, viverra  <span class="found">претензия</span> vitae congue eu, consequat ac felis?',
		operator: 'Татьяна',
		client: 'Марк',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 10,
		date: '2022-04-23 16:05',
		group: 'группа 2',
		categ: 'Оплата',
		record:
			'Nec tincidunt praesent  <span class="found">претензия</span> semper feugiat nibh sed pulvinar.',
		operator: 'Юлия',
		client: 'Давид',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 11,
		date: '2022-04-15 20:49',
		group: 'группа 3',
		categ: 'Продажи',
		record:
			'Vitae  <span class="found">претензия</span> turpis massa sed elementum tempus egestas sed!',
		operator: 'Софья',
		client: 'Ярослав',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 12,
		date: '2022-04-15 20:48',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Pulvinar mattis nunc, sed  <span class="found">претензия</span> blandit libero volutpat sed.',
		operator: 'Алина',
		client: 'Евгений',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 13,
		date: '2022-04-15 20:47',
		group: 'группа 2',
		categ: 'Продажи',
		record: 'Enim, sed faucibus  <span class="found">претензия</span> turpis in eu mi bibendum.',
		operator: 'Злата',
		client: 'Матвей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 14,
		date: '2022-04-15 20:46',
		group: 'группа 2',
		categ: 'Оплата',
		record:
			'Faucibus turpis in  <span class="found">претензия</span> eu mi bibendum neque egestas.',
		operator: 'Милана',
		client: 'Фёдор',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 15,
		date: '2022-04-15 20:45',
		group: 'группа 3',
		categ: 'Оплата',
		record:
			'Dictum varius  <span class="found">претензия</span> duis at consectetur lorem donec massa.',
		operator: 'Ольга',
		client: 'Николай',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 16,
		date: '2022-04-15 20:44',
		group: 'группа 1',
		categ: 'Сервис',
		record: 'Vel eros donec ac odio  <span class="found">претензия</span> tempor orci dapibus?',
		operator: 'Светлана',
		client: 'Алексей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 17,
		date: '2022-04-11 17:55',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Sem fringilla ut morbi tincidunt  <span class="found">претензия</span> augue interdum velit?',
		operator: 'Ярослава',
		client: 'Андрей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 18,
		date: '2022-04-11 17:54',
		group: 'группа 1',
		categ: 'Сервис',
		record: 'Purus, in mollis  <span class="found">претензия</span> nunc sed id semper risus!',
		operator: 'Яна',
		client: 'Артемий',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 19,
		date: '2022-04-11 17:53',
		group: 'группа 1',
		categ: 'Продажи',
		record: 'Senectus  <span class="found">претензия</span> et netus et malesuada fames ac turpis.',
		operator: 'Кристина',
		client: 'Виктор',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 20,
		date: '2022-04-10 17:53',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Scelerisque  <span class="found">претензия</span> mauris pellentesque pulvinar pellentesque habitant morbi tristique.',
		operator: 'Алиса',
		client: 'Никита',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 21,
		date: '2022-03-24 18:11',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'A,  <span class="found">претензия</span> condimentum vitae sapien pellentesque habitant morbi tristique.',
		operator: 'Маргарита',
		client: 'Даниил',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 22,
		date: '2022-03-24 18:10',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Dignissim convallis aenean et  <span class="found">претензия</span> tortor at risus viverra!',
		operator: 'Таисия',
		client: 'Денис',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 23,
		date: '2022-03-24 18:09',
		group: 'группа 1',
		categ: 'Оплата',
		record: 'At varius vel, pharetra vel  <span class="found">претензия</span> turpis nunc eget!',
		operator: 'Тамара',
		client: 'Егор',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 24,
		date: '2022-03-24 18:09',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'Et molestie ac,  <span class="found">претензия</span> feugiat sed lectus vestibulum mattis?',
		operator: 'Эмилия',
		client: 'Игорь',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 25,
		date: '2022-03-24 18:08',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Vitae justo eget  <span class="found">претензия</span> magna fermentum iaculis eu non?',
		operator: 'Диана',
		client: 'Лев',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 26,
		date: '2022-03-24 16:44',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Et tortor consequat id  <span class="found">претензия</span> porta nibh venenatis cras.',
		operator: 'Анфиса',
		client: 'Леонид',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 27,
		date: '2022-03-24 16:43',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Turpis egestas integer  <span class="found">претензия</span> eget aliquet nibh praesent tristique!',
		operator: 'Аделина',
		client: 'Павел',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 28,
		date: '2022-03-24 16:08',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'Tellus at urna  <span class="found">претензия</span> condimentum mattis pellentesque id nibh?',
		operator: 'Евдокия',
		client: 'Петр',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 29,
		date: '2022-03-24 16:07',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Hac habitasse  <span class="found">претензия</span> platea dictumst quisque sagittis, purus sit.',
		operator: 'Зоя',
		client: 'Роман',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 30,
		date: '2022-03-23 16:06',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Sit amet est placerat in  <span class="found">претензия</span> egestas erat imperdiet.',
		operator: 'Ираида',
		client: 'Руслан',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 31,
		date: '2022-03-23 16:05',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Viverra maecenas accumsan, lacus vel  <span class="found">претензия</span> facilisis volutpat, est?',
		operator: 'Наталья',
		client: 'Сергей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 32,
		date: '2022-03-15 20:49',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Varius morbi enim  <span class="found">претензия</span> nunc, faucibus a pellentesque sit!',
		operator: 'Пелагея',
		client: 'Семён',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 33,
		date: '2022-03-15 20:48',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Ac tincidunt vitae,  <span class="found">претензия</span> semper quis lectus nulla at.',
		operator: 'Сабина',
		client: 'Тимофей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 34,
		date: '2022-03-15 20:47',
		group: 'группа 1',
		categ: 'Продажи',
		record: 'Eu ultrices vitae, auctor eu  <span class="found">претензия</span> augue ut lectus!',
		operator: 'Антонина',
		client: 'Степан',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 35,
		date: '2022-03-15 20:46',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Morbi tristique  <span class="found">претензия</span> senectus et netus et malesuada fames?',
		operator: 'Екатерина',
		client: 'Владимир',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 36,
		date: '2022-03-14 20:45',
		group: 'группа 1',
		categ: 'Продажи',
		record: 'Orci, a scelerisque purus semper  <span class="found">претензия</span> eget duis at.',
		operator: 'Елена',
		client: 'Тимофей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 37,
		date: '2022-03-14 20:44',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Convallis convallis tellus, id  <span class="found">претензия</span> interdum velit laoreet id!',
		operator: 'Ксения',
		client: 'Ярослав',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 38,
		date: '2022-03-11 17:55',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Quis viverra nibh  <span class="found">претензия</span> cras pulvinar mattis nunc, sed!',
		operator: 'Ирина',
		client: 'Павел',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 39,
		date: '2022-03-11 17:54',
		group: 'группа 1',
		categ: 'Оплата',
		record: 'Id eu nisl  <span class="found">претензия</span> nunc mi ipsum, faucibus vitae.',
		operator: 'Ева',
		client: 'Егор',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 40,
		date: '2022-03-11 17:53',
		group: 'группа 1',
		categ: 'Продажи',
		record: 'Nam  <span class="found">претензия</span> aliquam sem et tortor consequat id porta.',
		operator: 'Дарья',
		client: 'Сергей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 41,
		date: '2022-03-10 17:53',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Amet  <span class="found">претензия</span> commodo nulla facilisi nullam vehicula ipsum a!',
		operator: 'Кира',
		client: 'Владислав',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 42,
		date: '2022-02-24 18:11',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'Dui vivamus arcu felis, bibendum  <span class="found">претензия</span> ut tristique et.',
		operator: 'Елизавета',
		client: 'Федор',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 43,
		date: '2022-02-24 18:10',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Erat pellentesque  <span class="found">претензия</span> adipiscing commodo elit, at imperdiet dui.',
		operator: 'Ульяна',
		client: 'Константин',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 44,
		date: '2022-02-24 18:09',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'Amet commodo  <span class="found">претензия</span> nulla facilisi nullam vehicula ipsum a?',
		operator: 'Татьяна',
		client: 'Максим',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 45,
		date: '2022-02-24 18:09',
		group: 'группа 1',
		categ: 'Сервис',
		record: 'Sed  <span class="found">претензия</span> euismod nisi porta lorem mollis aliquam ut.',
		operator: 'Юлия',
		client: 'Артём',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 46,
		date: '2022-02-24 18:08',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Integer  <span class="found">претензия</span> eget aliquet nibh praesent tristique magna sit!',
		operator: 'Софья',
		client: 'Никита',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 47,
		date: '2022-02-24 16:44',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'Donec adipiscing  <span class="found">претензия</span> tristique risus nec feugiat in fermentum.',
		operator: 'Алина',
		client: 'Григорий',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 48,
		date: '2022-02-24 16:43',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Condimentum lacinia quis  <span class="found">претензия</span> vel eros donec ac odio!',
		operator: 'Злата',
		client: 'Лев',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 49,
		date: '2022-02-24 16:08',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Est ante in nibh mauris,  <span class="found">претензия</span> cursus mattis molestie.',
		operator: 'Милана',
		client: 'Андрей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 50,
		date: '2022-02-24 16:07',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'Faucibus vitae  <span class="found">претензия</span> aliquet nec, ullamcorper sit amet risus!',
		operator: 'Ольга',
		client: 'Роман',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 51,
		date: '2022-02-24 16:06',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Morbi tincidunt  <span class="found">претензия</span> ornare massa, eget egestas purus viverra.',
		operator: 'Светлана',
		client: 'Арсений',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 52,
		date: '2022-02-23 16:05',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Mollis aliquam  <span class="found">претензия</span> ut porttitor leo a diam sollicitudin.',
		operator: 'Ярослава',
		client: 'Степан',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 53,
		date: '2022-02-15 20:49',
		group: 'группа 1',
		categ: 'Оплата',
		record: 'Et tortor  <span class="found">претензия</span> at risus viverra adipiscing at in.',
		operator: 'Яна',
		client: 'Владислав',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 54,
		date: '2022-02-15 20:48',
		group: 'группа 1',
		categ: 'Сервис',
		record: 'Volutpat  <span class="found">претензия</span> sed cras ornare arcu dui vivamus arcu?',
		operator: 'Кристина',
		client: 'Никита',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 55,
		date: '2022-02-15 20:47',
		group: 'группа 1',
		categ: 'Продажи',
		record:
			'Praesent semper  <span class="found">претензия</span> feugiat nibh sed pulvinar proin gravida.',
		operator: 'Алиса',
		client: 'Глеб',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 56,
		date: '2022-02-15 20:46',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Cursus in hac  <span class="found">претензия</span> habitasse platea dictumst quisque sagittis.',
		operator: 'Маргарита',
		client: 'Марк',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 57,
		date: '2022-02-15 20:45',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Quis lectus nulla at volutpat diam ut  <span class="found">претензия</span> venenatis.',
		operator: 'Таисия',
		client: 'Давид',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 58,
		date: '2022-02-15 20:44',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Nulla malesuada pellentesque  <span class="found">претензия</span> elit eget gravida cum sociis.',
		operator: 'Тамара',
		client: 'Ярослав',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 59,
		date: '2022-02-11 17:55',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Facilisi  <span class="found">претензия</span> nullam vehicula ipsum a arcu cursus vitae!',
		operator: 'Эмилия',
		client: 'Евгений',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 60,
		date: '2022-02-11 17:54',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Turpis massa  <span class="found">претензия</span> sed elementum tempus egestas sed sed.',
		operator: 'Диана',
		client: 'Матвей',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 61,
		date: '2022-02-11 17:53',
		group: 'группа 1',
		categ: 'Оплата',
		record:
			'Suspendisse sed nisi  <span class="found">претензия</span> lacus, sed viverra tellus in?',
		operator: 'Анфиса',
		client: 'Фёдор',
		expand: false,
		star: false,
		comment: '',
	},
	{
		id: 62,
		date: '2022-02-11 17:53',
		group: 'группа 1',
		categ: 'Сервис',
		record:
			'Sed pulvinar proin  <span class="found">претензия</span> gravida hendrerit lectus a molestie.',
		operator: 'Аделина',
		client: 'Николай',
		expand: false,
		star: false,
		comment: '',
	},
]

export { operators, records }
